name: WordOfTheDay
options:
  minimumXcodeGenVersion: 2.38.0
settings:
  base:
    SWIFT_VERSION: 5.10
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 1.0
    DEVELOPMENT_TEAM: Y497323X27
    CODE_SIGN_STYLE: Automatic
configs:
  Debug: debug
  Release: release
targets:
  WordOfTheDayApp:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: WordOfTheDayApp
      - path: Shared
    info:
      path: WordOfTheDayApp/Info.plist
      properties:
        CFBundleDisplayName: Kelime
        UILaunchScreen: {}
        CFBundleURLTypes:
          - CFBundleTypeRole: Editor
            CFBundleURLName: wordoftheday
            CFBundleURLSchemes:
              - wordoftheday
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.miqdam.wordoftheday
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1"
    dependencies:
      - target: WordOfTheDayWidgetExtension

  WordOfTheDayWidgetExtension:
    type: app-extension
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: WordOfTheDayWidget
      - path: Shared
    info:
      path: WordOfTheDayWidget/Info.plist
      properties:
        CFBundleDisplayName: Kelime
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.miqdam.wordoftheday.widgetv2
        APPLICATION_EXTENSION_API_ONLY: YES
