import Foundation

struct Word: Codable, Hashable, Identifiable {
    struct Example: Codable, Hashable {
        let tr: String
        let en: String
    }

    let id: String
    let word: String
    let meaning: String
    let partOfSpeech: String
    let level: String
    let tip: String
    let examples: [Example]
}

enum WordLibrary {
    /// Every word in schedule order. Generated by `tools/build_words.py`.
    static let all: [Word] = load()

    static func word(withID id: String) -> Word? {
        all.first { $0.id == id }
    }

    private static func load() -> [Word] {
        let bundles = [Bundle.main, Bundle(for: BundleAnchor.self)]
        guard let url = bundles.lazy.compactMap({ $0.url(forResource: "turkish_words", withExtension: "json") }).first,
              let data = try? Data(contentsOf: url),
              let words = try? JSONDecoder().decode([Word].self, from: data) else {
            assertionFailure("turkish_words.json is missing or invalid")
            return []
        }
        return words
    }
}

private final class BundleAnchor {}
